# .streamlit/config.toml

[theme]
primaryColor = "#0d1117"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#fcfcfc"
textColor = "#0d1117"

[server]
enableCORS = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true
hideSidebarNav = true
